### ISSUE TITLE
Incorrect contact information at openconext.org

### ISSUE THREAD

**Issue by jstevensog** [OpenConext/OpenConext-engineblock#1001]
Hello,
I have been trying to reach out through openconext@googlegroups.com as advised in the Contact section of openconext.org, but I receive bounce messages.
Note, this is my personal github account, but in my work I have a specific use case I am hoping OpenConext can assist with and wish to talk with someone regarding this case.
Please reach out to me directly and I will provide my work contact details.
Cheers

**Comment by surfnet-niels** [comment]
Hi, thanks for reaching out.
The list seems to work fine. Please know you need to subscribe to the list first before you are allowed to send stuff to it.
To subscribe use Googles GUI or send an email to  [Groupname]-subscribe@googlegroups.com.
Looking forward to you questions on the list

**Comment by jstevensog** [comment]
Still having issues.
Bounce message stating openconext-subscribe@googlegroups.com stating the account does not exist from my work e-mail address.  I will try again from my personal e-mail address.
Cheers
