### ISSUE TITLE
AssertionConsumerService:0:index is ignored

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#106]
We currently ignore :index from JANUS and instead use the numeric value in the key.

First this will work in most cases where the SP choses to use a 0 based ascending index:

```
<AssertionConsumerService ... index=0 />
<AssertionConsumerService ... index=1 />
<AssertionConsumerService ... index=2 />
```

Will indeed be mapped by the metadata importer into AssertionConsumerService:0, AssertionConsumerService:1 and AssertionConsumerService:2.

It will however break on any other mapping, like for instance 1 based ascending:

```
<AssertionConsumerService ... index=1 />
<AssertionConsumerService ... index=2 />
<AssertionConsumerService ... index=3 />
```

Will be mapped into AssertionConsumerService:0, AssertionConsumerService:1 and AssertionConsumerService:2.
Should this SP then request to use ACS with index 1, index 2 will be used instead. Even more puzzling the JANUS UI will appear to have the right index.
Also manually mapping an ACS 0 and 2 onto AssertionConsumerService:0 and AssertionConsumerService:2 is _not guaranteed_ to reach EngineBlock with an index 0 and 2.

This behaviour has probably evolved thusly because
a. SURFconext does not officially support AuthnRequests with an AssertionConsumerServiceIndex as that falls outside of [SAML2Int](http://saml2int.org).
b. Very few SPs use this (if any).
c. JANUS unfortunately can not prevent an admin for manually entering a ACS without an index.

Several solutions exist for this issue:
## 1. Accept the current behaviour.

Train the support team to expect and handle this eventuality should it occur.
## 2. Explicitly drop support for indexed based ACS.
- Remove the ':index' key from SR
- Log a WARN when an AuthnRequest uses a ACSIndex and use the default ACS
## 3. Explicitly support indexed based ACS.
- Migrate existing JANUS connections so that : x : will be filled in :index. This may mean that it will no longer match the SP metadata but it will match the current behaviour and can be adjusted upon issues.
- Make Engine use :index. Should JANUS NOT specify an index for an ACS it may fall back to : x : (though really the JANUS UI should be fixed).

**Comment by tvdijen** [comment]
I'm running into this same issue with an SP that only provides an ACS-index, not an ACS-location.
This leads to a lot of notices in the logfiles regarding fallback to the default ACS-location from the metadata.

**Comment by thijskh** [comment]
FYI: we try to follow saml2int https://saml2int.org/profile/current/. This does not allow the use of Index. And rightly so I think, because it's highly fragile. I therefore think it's not a big problem that the behaviour is now somewhat 'undefined' when you use it.

**Comment by thijskh** [comment]
Nonetheless this issue has been fixed now ( nr 3), bu changing Manage to send the right index values. EB handles this as expected.
