### ISSUE TITLE
Empower user to manage Identity Provider sessions

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#107]
If I log in with an Identity Provider I can only log in with another Identity Provider if the Service Provider happens to not support that Identity Provider.
In which case I will always log in with THAT Identity Provider.

I propose making this more transparant to the user:

On first encounter with EB you get the discovery screen without any preselected Identity Providers.
![screen shot 2014-12-05 at 13 45 58](https://cloud.githubusercontent.com/assets/524386/5315936/399fcb0a-7c85-11e4-81a3-4c55146ff6f8.png)

You select an IdP and log in. Then you go to a different SP automatically get redirected to:
![screen shot 2014-12-05 at 13 49 48](https://cloud.githubusercontent.com/assets/524386/5316015/495393d2-7c86-11e4-9e3e-863b9de9008a.png)

When you click stop you see:
![screen shot 2014-12-05 at 13 51 23](https://cloud.githubusercontent.com/assets/524386/5316018/558acbde-7c86-11e4-9a29-a18ee2f4ffbb.png)

With a "Previous" and "History" from which you can delete and among which you can delete.
Deleting will give you a warning that if you are still logged into "name of the idp" then you need to close the window (hard to do on mobile) or manually log out there.

**Comment by arnoutt** [comment]
Just a check to see whether I understand this correctly: do you propose to build in some sort of delay screen (with a stop button) (the 2nd picture) every time I login to another service while I am already logged in through Single Sign On?

**Comment by relaxnow** [comment]
Yup, that was the suggestion to help users select a different Identity Provider after they had already selected one.

Alternative might be to add a checkbox to the WAYF as in:

* [ ] Remember for x days.

**Comment by relaxnow** [comment]
Though with a checkbox the user is still out of luck if someone checked it for him (CSRF) or if he suddenly needs to log in at a different IdP (for example imagine a professor sitting with a student wanting to show him something).

**Comment by arnoutt** [comment]
Ah I see. I think there are only a couple of users that actually have more than 1 IdP so to build in a delay for only 0.01% of the users does not seem like a very good solution...

The second suggestion sounds good, but does not really solve the first problem :) What we are going to fix though is that the "preselected IdP" will *always* be the one you've selected last time. But that doesn't solve the problem you describe either.

**Comment by relaxnow** [comment]
Ah okay if you've measured that it's not really an issue then feel free to close this (power user) issue.

(Also just checked and the form is not vulnerable to CSRF because we require the AuthnRequest ID)

**Comment by thijskh** [comment]
Powerusers can easily use the <del>porn</del>private browsing button in their browser.

**Comment by arnoutt** [comment]
I suppose there is no way for a user to "disable" SSO and get a WAYF every time? (Similar to ForceAuthn)

**Comment by thijskh** [comment]
Not currently, no.
