### ISSUE TITLE
Improve handing in case of wrong ACS binding

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-engineblock#108]
Currently if a ACS binding http-redirect is requested by the IdP we return an error: 
"Invalid ACS Binding Type" (See below)
![selection_079](https://cloud.githubusercontent.com/assets/1491826/5357654/8146e34e-7faa-11e4-8096-986bbf64c8e8.jpg)

Find an example request below
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"
                  xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion"
                  AssertionConsumerServiceURL="https://t01.t.inacademia.org/svs/acs/redirect"
                  Destination="https://engine.surfconext.nl/authentication/idp/single-sign-on/key:20140505"
                  ForceAuthn="false"
                  ID="id-f583720f226fa3ded12abc65c9d17445"
                  IssueInstant="2014-12-09T12:41:06Z"
                  ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                  Version="2.0"
                  >
    <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://inacademia.org/metadata/t01-p-test.xml/ns1:Issuer
    <ns0:NameIDPolicy AllowCreate="false"
                      Format="u"
                      />
/ns0:AuthnRequest

Although the error is correct, the location of the error in the flow is weird: it is presented AFTER the user logged into the IdP. (see attached flow below) 
![selection_080](https://cloud.githubusercontent.com/assets/1491826/5357655/83bb86e8-7faa-11e4-971f-1881ef873617.jpg)
However we could have known we would not be able to answer this request the moment it came in...

**Comment by thijskh** [comment]
Don’t see this as a priority. Redirect binding is forbidden so the error is correct and this should not happen often. It would be slightly more convenient to report it a few seconds earlier but the error is reported correctly.
