### ISSUE TITLE
Feature - SSO Notifications

### ISSUE THREAD

**Issue by Jong-Vincent** [OpenConext/OpenConext-engineblock#1148]
We have added functionality to be able to process SSO Notifications. This is a feature to reduce the number of steps users have to take during the login process and increase user-friendliness by providing the possibility to skip the WAYF (Where Are You From) screen.
 
Please see #1147 for further details.

**Comment by tvdijen** [comment]
@Jong-Vincent Out of curiosity, how would this work in a hub&spoke federation with multiple hubs / WAYFs?
