### ISSUE TITLE
Fatal error with blank page on invalid XML input

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#118]
Example: https://engine.surfconext.nl/authentication/idp/single-sign-on?SAMLRequest=f

**Comment by thijskh** [comment]
The "blank page" has been fixed in EB 4.7; it now generates "Error - An error occurred" when this happens.

**Comment by thijskh** [comment]
The library will also log a more concrete error when this happens. Case closed.
