### ISSUE TITLE
Improve OpenConext privacy preservation by not sending saml:AuthenticatingAuthority

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-engineblock#130]
OpenConext currently sends saml:AuthenticatingAuthority as part of the saml assertion to every SP, e.g.  

``` xml
<saml:AuthenticatingAuthority>https://idp.surfnet.nl</saml:AuthenticatingAuthority>
```

which contains the IdP that handled the login. There is no technical need for this.

If the SP receives a very small set of attributes, this actually leaks information thus breaching privacy of the enduser.

It should be made configurable whether or not to send this, and preferably the default should be set to not sending this information.

**Comment by thijskh** [comment]
I believe that we are required to send this this way as per 3.4.1.5.1 of the SAML spec.

**Comment by thijskh** [comment]
Since this is required by the spec I don’t think we’ll change this.
