### ISSUE TITLE
Release a given regular attribute in the NameID

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#1301]
The SAML Subject NameID is set by Engineblock based on the SP's configuration to be a value generated by Engineblock, either persistent, transient or unspecified ID (collabPersonID).

Regularly services require the NameID to have the value of some specific other attribute that is released by the IdP, not generated by Engineblock. Most commonly email adress, eduPersonPrincipalName or uid. We now solve this with an attribute manipulation. However, we'd like EB to handle this in configuration for us.

A change has been made in Manage so that under the ARP for a given SP you can mark it as "release this attribute as name-id".

```json
   "arp_attributes" : {
      "urn:mace:dir:attribute-def:cn" : [
         {
            "use_as_name_id" : true,
            "motivation" : "Hiervoor wordt het gebruikt",
            "value" : "*"
         }
      ]
   },
```

When set to true the _first_ value of `urn:mace:dir:attribute-def:cn` will be used as the value for NameID. The NameID format can be set to the "unspecified" urn.

I propose this logic in the exising Corto output filter that handles NameID setting:
- If this is set for an attribute, release this attribute and set NameIDFormat to unspecified
- Otherwise use the NameIDFormat to determine value and format for any NameID, as it is now

Further considerations:
* When `use_as_name_id` is missing it needs to be assumed false
* Manage will guarantee that not more than one attribute in a given ARP will have set this to true.

**Comment by MKodde** [comment]
Sounds like a great way to further eliminate the use case for attribute aggregation. With the implementation of this feature, can we start thinking about turning AA off? Or are there other important use cases left to keep it around?
