### ISSUE TITLE
Adding SP without Assertion Consumer Binding / Locations registered in the Service Registry leads to php warnings

### ISSUE THREAD

**Issue by lvonk** [OpenConext/OpenConext-engineblock#133]
![screen shot 2015-02-12 at 11 58 11](https://cloud.githubusercontent.com/assets/104943/6166276/1e98fe8e-b2af-11e4-8c68-24a8b7b3c75e.png)

**Comment by thijskh** [comment]
Manage disaows this, seems sufficient
