### ISSUE TITLE
Stepup related logging shows wrong key_id

### ISSUE THREAD

**Issue by quartje** [OpenConext/OpenConext-engineblock#1343]
I am not quite sure what it is that is logged in the key_id in stepup related logs. eg:
```
{"channel":"app","level":"WARNING","message":"After Stepup authentication update received LoA","context":{"key_id":"_2B40C7186DC7624C4804DE96F9454826","result":{}},"extra":{"session_id":"teia448dodmj9ea57sqegcjf4k","request_id":"6745867f3dd09"}}
```

The key_id for other logs is the id of the SAML signing key.

**Comment by tvdijen** [comment]
Could this be related to https://github.com/OpenConext/OpenConext-engineblock/issues/1241 ?
