### ISSUE TITLE
Character encoding issue with spentityname in EB log_logins

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-engineblock#136]
The query:
```
SELECT spentityname, HEX(spentityname) FROM eb.log_logins WHERE id = <some row id>;
```
returns:
```
'GÃ‰ANT Intranet | eduGAIN', '47C389414E5420496E7472616E6574207C206564754741494E'
```

Table definition:
```
CREATE TABLE `log_logins` (
  `loginstamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userid` varchar(1000) NOT NULL,
  `spentityid` varchar(1000) DEFAULT NULL,
  `idpentityid` varchar(1000) DEFAULT NULL,
  `spentityname` varchar(1000) DEFAULT NULL,
  `idpentityname` varchar(1000) DEFAULT NULL,
  `useragent` varchar(1024) DEFAULT NULL,
  `voname` varchar(1024) DEFAULT NULL,
  `keyid` varchar(50) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=146322927 DEFAULT CHARSET=latin1;
```
```0xC3 0x89``` is the UTF-8 encoding for "É" (```0xC9``` in Latin-1) . I.e. The UTF-8 byte representation was wrongly interpreted as Latin-1 somewhere along the way.

The string with the SP name is correct when EB retrieves it from janus:
```
curl 'https://serviceregistry..../module.php/janus/services/rest/?method=getEntity&entityid=http...&janus_key=engineblock&userid=engineblock&janus_sig=...&rest=1'
```
Returns:
```
{"eid":"1295","entityid":"http:\/\/weblogin2.geant.net\/adfs\/services\/trust","revision":"6","parent":"5","revisionnote":"cxt-7230","type":"saml20-sp","allowedall":"yes","workflow":"prodaccepted","metadataurl":null,"prettyname":"G\u00c9ANT Intranet | eduGAIN","arp":{"urn:mace:terena.org:attribute-def:schacHomeOrganization":["*"],"urn:mace:dir:attribute-def:displayName":["*"],"urn:mace:dir:attribute-def:cn":["*"],"urn:mace:dir:attribute-def:givenName":["*"],"urn:mace:dir:attribute-def:sn":["*"],"urn:mace:dir:attribute-def:mail":["*"],"urn:mace:dir:attribute-def:eduPersonPrincipalName":["*"],"urn:mace:dir:attribute-def:eduPersonAffiliation":["*"],"urn:mace:dir:attribute-def:eduPersonTargetedID":["*"]},"manipulation":"","user":"..."}
```

**Comment by pmeulen** [comment]
We should set the client character set to utf8 when creating the mysql DB connection from EB, and not rely on defaults in schema's or my.conf.

**Comment by relaxnow** [comment]
It looks like the character set for the table has been set to latin1 and unfortunately while the OpenConext-vm has it's own database definitions where it does set the character set to utf8, OpenConext-deploy uses EBs own migrations where no character set is specified: https://github.com/OpenConext/OpenConext-engineblock/blob/master/database/patch/patch-0002.sql#L202
So it will use the default which is latin1 unfortunately.

I propose the following:
0. Check for latin1 on all SURFconext production schemas.
1. Roll up EBs database patches and set the character set to utf8_general_ci.
2. Add a new database patch that sets the character set to utf8_general_ci (no conversion is needed).
3. Make EB connect using the character set ( http://stackoverflow.com/a/4361485/4512 ).
4. Make utf8_general_ci the default character set in my.cnf for OpenConext-deploy ( https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/mysql/tasks/main.yml )

**Comment by pmeulen** [comment]
+1

**Comment by thijskh** [comment]
This has already been fixed for new installations. Furthermore, `log_logins` is obsoleted in 5.0.
