### ISSUE TITLE
WAYF for EB debug page does not show any IdP

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#138]
Since EB 4.4.0, logging into the EB debug page shows a WAYF without any IdP in it:
![screenshot from 2015-03-31 11 12 29](https://cloud.githubusercontent.com/assets/3808792/6915725/d7b55adc-d796-11e4-9b3e-069211ca5191.png)

If you already have an EB session, the WAYF is skipped as expected and then the debug page works as expected.

**Comment by relaxnow** [comment]
![screen shot 2015-06-17 at 09 34 37](https://cloud.githubusercontent.com/assets/524386/8201765/205debd0-14d4-11e5-96a3-fe6a2dcb3cf5.png)

works for me.
