### ISSUE TITLE
SuperGlobalManager log attachments are attached to an arbitrary log call

### ISSUE THREAD

**Issue by rjkip** [OpenConext/OpenConext-engineblock#143]
`SuperGlobalManager#injectOverrides()` currently add attachments to any arbitrary log call that succeeds it, as it [attaches them after the relevant log call](https://github.com/OpenConext/OpenConext-engineblock/blob/0783a1b0e8cb794d07f20be2b7f68fe20b3422a6/library/EngineBlock/Application/SuperGlobalManager.php#L37-L38).

**Comment by thijskh** [comment]
Fixed in 4.6.0

**Comment by rjkip** [comment]
Confirmed :+1:
