### ISSUE TITLE
SuperGlobalManager attaches incorrect super global value

### ISSUE THREAD

**Issue by rjkip** [OpenConext/OpenConext-engineblock#144]
`SuperGlobalManager#injectOverrides()` attaches the super global value that is about to be overridden to the log call. However, [it reads the value from `$_SERVER`](https://github.com/OpenConext/OpenConext-engineblock/blob/0783a1b0e8cb794d07f20be2b7f68fe20b3422a6/library/EngineBlock/Application/SuperGlobalManager.php#L37), while it [can be any super global](https://github.com/OpenConext/OpenConext-engineblock/blob/0783a1b0e8cb794d07f20be2b7f68fe20b3422a6/library/EngineBlock/Application/SuperGlobalManager.php#L33).

**Comment by thijskh** [comment]
Fixed in 4.6.0, correct?

**Comment by rjkip** [comment]
Looks like it :+1:
