### ISSUE TITLE
ServiceProvider given, array expected during unsollicited single sign-on

### ISSUE THREAD

**Issue by rjkip** [OpenConext/OpenConext-engineblock#149]
[Here](https://github.com/OpenConext/OpenConext-engineblock/blob/2c744d9e9d6861d7b53113f149c6785e18406983/library/EngineBlock/Corto/Module/Service/SingleSignOn.php#L134-L139), the `$remoteEntity` is always given a `ServiceProvider`.

**Comment by relaxnow** [comment]
Thanks!
