### ISSUE TITLE
Hardcoded SHO+uid requirement in library/EngineBlock/Saml2Attributes/FieldMapper.php

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-engineblock#154]
There is a hard-coded requirement for SHO + uid in library/EngineBlock/Saml2Attributes/FieldMapper.php

When changing the required attributes to ie ePPN, engine still is complaining when SHO and/or uid are not available. 

Also one must be a real EXPERT, since the subjectIdAttribute is case sensitive in engineblock.ini and must be camelcase for ePPN.

/etc/surfconext/engineblock.ini

``` ini
; Which LDAP attribute to use as the primary identifier.
; EXPERT use only!
; Recommend only using one of the following possible values:
; 'collabpersonid', 'collabpersonuuid', 'edupersonprincipalname'
subjectIdAttribute = "eduPersonPrincipalName"
```

**Comment by remold** [comment]
More info to switch to ePPN. This should be dynamic based upon subjectIdAttribute from the config:

diff --git a/library/EngineBlock/Saml2Attributes/FieldMapper.php b/library/EngineBlock/Saml2Attributes/FieldMapper.php
index 9004517..74274dd 100644
--- a/library/EngineBlock/Saml2Attributes/FieldMapper.php
+++ b/library/EngineBlock/Saml2Attributes/FieldMapper.php
@@ -7,8 +7,7 @@ class EngineBlock_Exception_MissingRequiredFields extends EngineBlock_Exception
 class EngineBlock_Saml2Attributes_FieldMapper
 {
     protected $_saml2Required = array(
-        'urn:mace:dir:attribute-def:uid',
-        'urn:mace:terena.org:attribute-def:schacHomeOrganization',
+        'urn:mace:dir:attribute-def:eduPersonPrincipalName'
     );
     /**

**Comment by relaxnow** [comment]
saml2Required has been superseded by use of the (configurable) attribute definition so should be removed.

EPPN shouldn't be in camelcase, collabPersonId isn't either? In fact LDAP is case agnostic with regards to it's field names I believe?

**Comment by thijskh** [comment]
Code has been removed in 5.3.0.
