### ISSUE TITLE
Hardcoded SHO+uid requirement in library/EngineBlock/UserDirectory.php

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-engineblock#156]
When switching the configuration subjectIdAttribute to eduPersonPrincipalName the functions in UserDirectory still use old values.

    diff --git a/library/EngineBlock/UserDirectory.php b/library/EngineBlock/UserDirectory.php
    index 26b0f89..e316c9b 100644
    --- a/library/EngineBlock/UserDirectory.php
    +++ b/library/EngineBlock/UserDirectory.php
    @@ -51,8 +51,12 @@ class EngineBlock_UserDirectory
          */
         public function findUsersByIdentifier($identifier)
         {
    +        $subjectIdField = EngineBlock_ApplicationSingleton::getInstance()->getConfigurationValue(
    +            'subjectIdAttribute',
    +            self::LDAP_ATTR_COLLAB_PERSON_ID
    +        );
             $filter = '(&(objectclass=' . self::LDAP_CLASS_COLLAB_PERSON . ')';
    -        $filter .= '(' . self::LDAP_ATTR_COLLAB_PERSON_ID . '=' . $identifier . '))';
    +        $filter .= '(' . $subjectIdField . '=' . $identifier . '))';
    
             $collection = $this->_ldapClient->search(
                 $filter,
    @@ -257,8 +261,16 @@ class EngineBlock_UserDirectory
    
         protected function _getCollabPersonId($attributes)
         {
    -        $uid = str_replace('@', '_', $attributes['uid']);
    -        return self::URN_COLLAB_PERSON_NAMESPACE . ':' . $attributes['o'] . ':' . $uid;
    +        $subjectIdField = EngineBlock_ApplicationSingleton::getInstance()->getConfigurationValue(
    +            'subjectIdAttribute',
    +            EngineBlock_UserDirectory::LDAP_ATTR_COLLAB_PERSON_ID
    +        );
    +        if ($subjectIdField == EngineBlock_UserDirectory::LDAP_ATTR_COLLAB_PERSON_ID) {
    +            $uid = str_replace('@', '_', $attributes['uid']);
    +            return self::URN_COLLAB_PERSON_NAMESPACE . ':' . $attributes['o'] . ':' . $uid;
    +        } else {
    +            return $attributes[$subjectIdField];
    +        }
         }
    
         protected function _getCollabPersonUuid($attributes)

**Comment by relaxnow** [comment]
I don't see a functional problem here? 
In fact this was a feature to ensure that EB will always have a proper collabpersonid instead of trying to force an alien value into the collabpersonid LDAP field.

Also this breaks the invariant between the DN and the primary identifier meaning that it makes it possible to get in a state where EB thinks a user does not exist yet, but LDAP disagrees as the DN already exists.
