### ISSUE TITLE
WAYF fails for IdP with numeric entityid

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#158]
When an IdP is created with a numeric **name** (like "2") this will be passed to the JavaScript as a Number and any sorting will fail because of disparate types (String and Number).

We could cast the Number to a String in JavaScript but ideally this would never be a Number (or PHP int) in the first place.

Note that this is low priority because a name should probably not be only a number.

![screen shot 2015-06-18 at 09 43 16](https://cloud.githubusercontent.com/assets/524386/8226389/ec7ca404-158d-11e5-9dc5-b70028f71a62.png)
![screen shot 2015-06-18 at 09 44 09](https://cloud.githubusercontent.com/assets/524386/8226392/f12a805c-158d-11e5-8ea6-db716b746cca.png)
![screen shot 2015-06-18 at 09 44 38](https://cloud.githubusercontent.com/assets/524386/8226396/f604441e-158d-11e5-9308-b76ca1415187.png)

**Comment by thijskh** [comment]
Fixed with the UI redesign in EB 4.5.
