### ISSUE TITLE
Tuple (entity_id,type) should be UNIQUE in sso_provider_roles

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#160]
The combination (`entity_id`, `type`) should always be unique in `sso_provider_roles`. This is currently not enforced in the database schema. It would be good to do so, to detect malformed content immediately.

**Comment by relaxnow** [comment]
Also ```sso_provider_roles``` is missing indexes for ```type``` and ```entityid``` (and possibly ```publish_in_edugain```).

**Comment by relaxnow** [comment]
Can be done manually with this SQL:

```sql
CREATE UNIQUE INDEX `idx_sso_provider_roles_entity_id_type`  ON `sso_provider_roles` (type, entity_id)
CREATE INDEX `idx_sso_provider_roles_publish_in_edugain`  ON `sso_provider_roles` (publish_in_edugain)
CREATE INDEX `idx_sso_provider_roles_entity_id`  ON `sso_provider_roles` (entity_id)
CREATE INDEX `idx_sso_provider_roles_type`  ON `sso_provider_roles` (type)
```

Though should also be encoded in the Doctrine entities so they are not lost on a subsequent update.
