### ISSUE TITLE
Login timestamps should not be stored as strings

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#161]
In its logging information, EB write login timestamps to the log_logins database as strings in the form "2015-12-01 13:45:33".
Please don't do that and use a proper timestamp field.

**Comment by thijskh** [comment]
Does this cause a concrete problem?

**Comment by baszoetekouw** [comment]
It makes processing statistics quite a bit harder and slower.  Nothing I can't work around (so not an urgent problem), but please take this into account if/when logging is overhauled.

**Comment by thijskh** [comment]
Bas confirmed they are in fact not stored as strings already.
