### ISSUE TITLE
EB sends NoPassive and ProxyCountExceeded as top-level status codes

### ISSUE THREAD

**Issue by rjkip** [OpenConext/OpenConext-engineblock#166]
[`ProxyServer#createErrorResponse()`](https://github.com/OpenConext/OpenConext-engineblock/blob/ab278d7b2686628b4efdcbe8897470a30b611e53/library/EngineBlock/Corto/ProxyServer.php#L397) sets the given error code on the `Code` status key. This means that [ProxyCountExceeded](https://github.com/OpenConext/OpenConext-engineblock/blob/9273c9c48d68243e443329433b212630e6971e13/library/EngineBlock/Corto/Module/Service/SingleSignOn.php#L55) and [NoPassive](https://github.com/OpenConext/OpenConext-engineblock/blob/9273c9c48d68243e443329433b212630e6971e13/library/EngineBlock/Corto/Module/Service/SingleSignOn.php#L98) codes are sent as top-level status codes.

If this doesn't affect SAML consumers of EngineBlock, or this is an acceptable fact, the status code should be assigned to the `SubCode` key, and `Code` should be assigned `SAML2_Const::STATUS_RESPONDER` or be set from a parameter.

See [the SAML spec](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf), line 1624 and the `SAML2_Const` constants documentation.

**Comment by arothuis** [comment]
This has been fixed and tested in #357.
