### ISSUE TITLE
EB 4.4 scoped metadata fails for idps in testaccepted state

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#172]
When requesting the scoped idps-metadata, it fails when the respective SP is in testaccepted, rather than prodaccepted state.

`Aug 13 18:07:29 t03 EBLOG[30052]: > QUEUED TIMESTAMP: 2015-08-13T18:07:29+02:00| EB[0ZZbuXVhfoxxCMrCdgxjw-rOn4f][55ccc0c0a8e4b] [Message ERR] Unable to find EngineBlock configured as Identity Provider. No 'https://engine.test2.surfconext.nl/authentication/idp/metadata' in repository!`

Example URL: https://engine.test2.surfconext.nl/authentication/proxy/idps-metadata?sp-entity-id=https://sp.testshib.org/shibboleth-sp

**Comment by relaxnow** [comment]
Fixed in 4.4.11.
