### ISSUE TITLE
Remove `libxml_disable_entity_loader()` call

### ISSUE THREAD

**Issue by DRvanR** [OpenConext/OpenConext-engineblock#180]
As requested by @relaxnow:

On [line 159 of the Application Bootstrapper file][1] the function `libxml_disable_entity_loader()` is called to safeguard against XML External Entity Injection. This should no longer be needed as it is now being done in the SAML2 lib that is used to parse SAML messages.

[1]: https://github.com/OpenConext/OpenConext-engineblock/blob/4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L159

**Comment by thijskh** [comment]
The README of saml2 says:
<blockquote>Ensure that before calling any code from this library you have called libxml_disable_entity_loader(true); this is required to prevent the XXE Processing Vulnerability</blockquote>

**Comment by relaxnow** [comment]
This issue depends on https://github.com/simplesamlphp/saml2/pull/49

**Comment by DRvanR** [comment]
Made a slightly different implementation

**Comment by DRvanR** [comment]
Sorry, pressed wrong button :wink:

**Comment by thijskh** [comment]
So if I'm correct the fix for this is to upgrade to saml2 ~ 1.7 and replace any remaining DOMDocument creation in the EB source code with the right call to a SAML2_DOMDocumentFactory method.
