### ISSUE TITLE
Transparent NameID checkbox

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-engineblock#195]
Many Attribute Manipulation scripts map the original NameID to the new NameID using this code:
$response['__']['CustomNameId'] = $response['__']['OriginalResponse']['__']['OriginalNameId'];

It would be nice to have a Service Registry checkbox for that.

**Comment by maartenk** [comment]
+1

**Comment by thijskh** [comment]
I see where you come from. However, I believe the cases where this is used is always to support some legacy scenario. We don't gain any new SP's that require this. So I'm not sure if we should prioritize it currently.

**Comment by thijskh** [comment]
I think we should remove it instead.
