### ISSUE TITLE
Make use of hashing algorithm configurable per SP

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#201]
EB currently uses SHA1 to sign its SAML assertions. It would be nice to be able to upgrade this hashing algorithm. However, we cannot do a big-bang change so we want the hashing algorithm to use to be configurable per SP in the serviceregistry.

**Comment by mrvanes** [comment]
For those looking to configure this globally, that's not possible. There is however one line that determines outgoing signature method in library/EngineBlock/X509/PrivateKey.php:27
Change that to SHA256 and all outgoing responses will be signed 256.

**Comment by thijskh** [comment]
Fixed in EB 5.6.
