### ISSUE TITLE
Attribute validation: distinquish between warning and error on debug page

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#207]
The attribute schema allows to define attribute validation errors (uid missing, sho missing) and warnings (displayName missing, mail missing). However, the difference between the two cannot be seen on the debug page:
![attributevalidation](https://cloud.githubusercontent.com/assets/3808792/10939954/7a0047f6-8305-11e5-9357-39bdccc459f2.png)

They could have a clearly different icon, but also the text could differ ("requires at least" vs "should have").

**Comment by arothuis** [comment]
Closing as this has been implemented in #368
