### ISSUE TITLE
EB 4.5 cuts off log messages

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-engineblock#217]
The new logging implementation no longer has chunking so rsyslog cuts off messages.

https://github.com/OpenConext/OpenConext-deploy will need to set a proper ```maxmessagesize``` for EB. @thijskh could you investigate, based on the current logs how high this setting needs to be?

**Comment by DRvanR** [comment]
as reference: for SSA [32k is used][1]

[1]: https://github.com/SURFnet/Stepup-Deploy/blob/46ee1d0e014efbdab5736e50dcace6f4d178a794/roles/common/templates/rsyslog/rsyslog.conf.j2#L8-L9

**Comment by quartje** [comment]
maxmessagesize can be changed to 32k. The syslogserver settings have been modified accordingly.
