### ISSUE TITLE
RequesterID is removed from request

### ISSUE THREAD

**Issue by quartje** [OpenConext/OpenConext-engineblock#224]
Adding the RequesterID is a configurable metadata entry for an IdP. 
In version 4.6.3 the RequesterID is added in the request to the IdP, but in version 4.7 it is missing.

**Comment by relaxnow** [comment]
This appears to be a bug in the SAML2 library, PR with fix can be found here: https://github.com/simplesamlphp/saml2/pull/56

Once that can be merged a new release will have to be made and EB can be upgraded.
This bug is only part of the 1.7.0 / 0.8.0 release. Thus it only affects EB 4.7 for now.
