### ISSUE TITLE
Allow for attribute manipulation in EB on request by PDP

### ISSUE THREAD

**Issue by oharsta** [OpenConext/OpenConext-engineblock#225]
This issue has been discussed with the TPM's and is scheduled for 2016.

Conform afspraak een voorstel voor attribute manipulatie in EB naar aanleiding van een PDP policy:
* SP is gemarkeerd als zijn “coin:policy_enforcement_decision_required”
* XACML Policy voor deze SP (met eventueel IdP’s) met daarin een “urn:collab:group:surfteams.nl” of / en “urn:collab:sab:surfnet.nl” attribuut met 1 of meerdere waardes (respectievelijk fully qualified team namen en sub rollen)
* Bij een PERMIT besluit van PDP voor deze policy wordt de teamnaam of rol die de eerste match binnen een policy opleverde (op basis van "urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" zie ook http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html#_Toc325047276) terug gegeven aan EB in de PDP response (de spec ondersteunt dit)
* EB voegt deze ene attribuut waarde toe aan de attributen die richting SP gaan
* De SP weet de rol van de gebruiker

Wat er nog moet gebeuren hiervoor is:
* In EB de daadwerkelijk attribuut manipulatie en de juiste naam kiezen voor de deze twee attributen
* Documentatie in PDP GUI dat de volgorde van attribuut waardes voor SAB en team namen wel degelijk uitmaakt als een SP beslissingen gaat nemen op basis hiervan (e.g. Dashboard / CSA)

**Comment by baszoetekouw** [comment]
Ik zou willen voorstellen om 2 eduPersonEntitlements te gebruiken met de volgende waarden:
`urn:x-surfnet:surfconext:pdp:pip-id:<pipnaam>` en `urn:x-surfnet:surfconext:pdp:pip-value:<attribuutvalue>`.
`<pipnaam>` kan dan zoiets zijn als `teams.surfconext.nl` of `sab.surfnet.nl`, en `attribuutvalue` kan de volledige groep of volledige sab-role bevatten.

@thijskh, is dat wat jou betreft akkoord?

**Comment by thijskh** [comment]
I think this is fine, but we should avoid hardcoding the string "surfconext" in OpenConext if possible.

**Comment by thijskh** [comment]
I have thought some more about this issue and I am not sure that we should implement this.

It's a pragmatic plan to get some additional information to SP's so those SP's don't have to create another query interface. 

This optimisation is nice to have, but it does lead to in my opinion a bit of a hackish setup where authorization rules are overloaded to also become attribute providers, which is quite a different function. It is also limited in what scenarios it supports. I could welcome this as a pragmatic choice to relieve SP's of the burden of looking this info up themselves, if there wasn't an idea of how to achieve the same goal. However, we do have concrete plans to make attribute aggregation possible which will achieve the same level of comfort for SP's in the longer run, while being more architecturally and conceptually sound.

If we introduce this feature now, it will be used and we will then later have to invest to migrate away from that. Also, the current setup works for our current SP's. Therefore, I'd much rather wait for proper AA support than to take this road.

**Comment by oharsta** [comment]
I agree. The plan to provide EB with the attributes that determined the policy decision was conjured when Attribute Aggregation was not yet on the radar. I'm closing this issue. However we do need to think about the VOOT and SAB Policy Information Points in PDP. These should eventually be removed in favour of Attribute Aggregation, but then you'll need to add an Attribute Aggregation when you create a policy in PDP that relies on either VOOT or SAB memberships. Keeping the VOOT and SAB PIPs is an unwanted duplication / overlap with AA.
