### ISSUE TITLE
Remove automagic attribute creation in LDAP from EB

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-engineblock#24]
EB contains code in several places where name related attributes (e.g. commonname, displayname, commonname, surname) attributes are created when the IdP does not provide one of these attributes. We should not do this. It is the IdP that is authoritative for these attributes, not OpenConext. In many cases the values of the created attributes will not be what is desired. EB itself does not require these attributes to function, other parts of OpenConext (Grouper, teams though the LDAP) currently do. The LDAP schema used requires sn and cn because the entries used have classes inetOrgPerson and organizationalPerson.

Since OpenConext requires cn and sn to function these we should either make these attributes mandatory to IdPs and enforce this by providing a (friendly) error to the user during login or remove the requirement. The first option is relatively simple to implement.

Code creating attributes in LDAP:
https://github.com/OpenConext/OpenConext-engineblock/blob/develop/library/EngineBlock/UserDirectory.php#L233

**Comment by relaxnow** [comment]
So ```sn``` and ```cn``` from the inetOrgPerson schema are MUST attributes: https://tools.ietf.org/html/rfc2798#section-3

Which is why we guarantee that ```cn``` always set. Interestingly we make no such guarantees for ```sn```. But even with a minimal IdP like Mujina I can't remember ever hearing the LDAP complain about needing an ```sn```?

**Comment by thijskh** [comment]
In 5.0 using LDAP is now optional.

**Comment by thijskh** [comment]
LDAP code has been remove in 5.3.0.
