### ISSUE TITLE
Missing info when error 'Invalid Identity Provider response' occurs

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#243]
When trying to login to, for example, Profile using the IdP UnitedID the error 'Error - Invalid Identity Provider response' occurs. This is because of https://github.com/OpenConext/OpenConext-engineblock/commit/615f9945ca7b025869328b7cac018124c500d0f3.

UnitedID uses encrypted assertions, so probably that's why the table with technical info can't be shown. However, things like Unique Request ID, IP address, User Agent and such *can* be shown.

This currently does not happen, see screenshot.

![screen shot 2016-01-14 at 11 21 39](https://cloud.githubusercontent.com/assets/8791564/12322766/738d919c-bab6-11e5-8600-8c1a69812f6e.png)

**Comment by thijskh** [comment]
This is supposedly fixed in EB 4.7. Can you verify this on test or acc?

**Comment by arnoutt** [comment]
Verified; in the release that is currently on the 4th set this problem is indeed fixed.
