### ISSUE TITLE
Proper error message needed when PDP fails

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#249]
Currently, if EB asks the PDP for an authorization decision, and the request fails (for example because of bad credentails), it throws an "Error: an error occured"-error.  Please chnage this to a more friendly error, for example: "authorization decision failed, please try again later or contact support@surfconext.nl".

**Comment by oharsta** [comment]
https://github.com/OpenConext/OpenConext-engineblock/commit/9b75f34c5a176b134e601dadb2364664dafb2bb5
