### ISSUE TITLE
Order of AuthZ and Consent

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#250]
Currently, the user is asked for consent before authz-processing is done.  If authz fails (user had no access), this leaves the impression that the attributes have been transferred to the SP anyway.

Please switch the order of AuthZ and Consent.

**Comment by oharsta** [comment]
This has been already fixed and merged into the 5.x-dev branch. Note that the PDP must be queried before the Attribute Release Policy is applied. See https://github.com/OpenConext/OpenConext-engineblock/commit/8216981440e6731595e719580ad7f1abfdded0f2
