### ISSUE TITLE
sp/debug does not adaptively log original SAML response

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-engineblock#256]
Normally, on error engineblock now adaptively logs the offending SAML respons.
This is not the case for the internal authentication/sp/debug page however, which makes debugging errors on sp/debug harder than they should be with the new logging server in place.

**Comment by thijskh** [comment]
You mean when you get an error on the debug page, it does not log the response? Do you have an error id from a case where that happened?

**Comment by mrvanes** [comment]
Yes, exactly that. 56a760ec8fc28

**Comment by thijskh** [comment]
Agreed, it does not have an `engineblock.DEBUG: SAML2 library debug message (in)` message.
