### ISSUE TITLE
Arrow keys in WAYF do not work (anymore)

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#260]
A user used to be able to navigate through the WAYF (up and down) using the arrow keys. This currently does not work.

To reproduce:
- Go to https://profile.surfconext.nl
- Type 'surf' in the input field
- Try using the arrow keys to scroll down to SURFnet

This happens on multiple browsers (Firefox, IE11, Chrome, Safari).

**Comment by thijskh** [comment]
This has been broken in EB 4.7, specifically in ef80d9d0ac0474a1c282ccfa69da98a4a716e74e, more specifically the first hunk of discover.phtml. Reverting that specific hunk restores the arrow key behaviour.

**Comment by arothuis** [comment]
This has been implemented in #337.
