### ISSUE TITLE
database password is shown in debug logs

### ISSUE THREAD

**Issue by quartje** [OpenConext/OpenConext-engineblock#263]
When a database error like the following occurs the password is shown plaintext in the debug log:
engineblock.ERROR: An exception occured in driver: SQLSTATE[08004] [1040] Too many connections
In this context for example:

/opt/openconext/OpenConext-engineblock-4.7.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php(216): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'leaked_username', 'leaked_password',

**Comment by thijskh** [comment]
This is something in Doctrine/DBAL/PDO that we cannot readily fix on our own. There's some work to be able to do this https://wiki.php.net/rfc/redact_parameters_in_back_traces. I don't think it's useful for us to keep this issue open, we'll have to accept it I'm afraid.
