### ISSUE TITLE
Ordering in discovery screen when searching

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#288]
When searching the discovery screen, sometimes "strange" matches appear at the top of the list.  For example, when searching for "idin", all kinds of strange matches appear before the actual "Idin IdP":

![screenshot_20160411_141503](https://cloud.githubusercontent.com/assets/1461740/14426515/d21504ec-ffef-11e5-9185-ec7aae0bea59.png)

It turns out that the "weird" entries are matching "ople**idin**gen".  

Instead of ordering all matches alphabetically, it would make more sense to sort "likely" matches (eg., matching a full keyword, or matching the IdP name, etc) on top, and "unlikely" matches (eg., partial matches in the middle of a word) on the bottom.

**Comment by thijskh** [comment]
Fixed in 6.4

**Comment by baszoetekouw** [comment]
w00t!
