### ISSUE TITLE
Detect browser locale setting to determine default language

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#293]
Upon first visit, the locale setting of the user's browser should be detected to determine the language of the page. Currently in SURFconext, only Dutch and English are supported. If a Dutch locale is detected, the page should be rendered in NL; otherwise (if any other language is detected of no language is detected), the page should be rendered in EN.

The language setting should be remembered (in a cookie?) and should be used on all pages (WAYF, consent, profile, error messages). If a user manually switches to another language, this should obviously be remembered as well.

**Comment by thijskh** [comment]
Indeed use `Accept-Language` to determine the default/initial language. Because this information is available in every browser request, we need not store it anywhere.

I would only store it in a cookie if the user manually selects a different language, as an override.

**Comment by arnoutt** [comment]
+1

**Comment by thijskh** [comment]
Fixed in 5.3
