### ISSUE TITLE
Bug in consent when IdP returns transient nameID

### ISSUE THREAD

**Issue by oharsta** [OpenConext/OpenConext-engineblock#294]
Bug in  [Consent](https://github.com/OpenConext/OpenConext-engineblock/blob/5.x-dev/library/EngineBlock/Corto/Model/Consent.php#L162) for the check if consent is already given:

``` php
$query = "SELECT * FROM {$this->_tableName} WHERE hashed_user_id = ? AND service_id = ? AND attribute = ? AND consent_type = ?”;
```

The hashed_user_id is a sha1 of the Response NameID. But for transient NameID's this is every time different when somebody logs. If the NameID of the Response is transient then the hashed_user_id should be the unspecified urn.

**Comment by thijskh** [comment]
We specify that we use the uid and schacHomeOrganization as the key for any user, and thus that as long as the IdP keeps those consistent, nothing will change. This is apparently not true, and should indeed be fixed.

**Comment by thijskh** [comment]
I've tried to verify this behaviour and cannot confirm it. The code uses NameId but at this point this is the collabpersonid (`urn:collab:person:…`) not the targeted SP-nameid that can be persistent of transient. If I log in twice to an SP with transient nameid, I get asked for consent only the first time which seems to confirm this reading.

Did you actually observe problems with this?
