### ISSUE TITLE
Session-lost error not triggered in processWayf

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#295]
EB has a dedicated error for "Session lost" (`/authentication/feedback/session-lost`) which describes that the session has been lost and list possible causes, such as disabled cookies.

This error page is not triggered when the corresponding exception happens in process-wayf. This is however a very likely place for it to occur. If you completely block cookies (for EB or at all), this is the first point where this exception happens.

Steps to reproduce:
1. Disable cookies in browser
2. Go to any SP; be redirected to WAYF.
3. Select an IdP in WAYF.
4. EB says: "Error - An error occurred". Logs reveal that `EngineBlock_Corto_Module_Services_SessionLostException` was thrown with message "Session lost after WAYF", but this was not caught.

**Comment by arothuis** [comment]
I'm having trouble reproducing this with the steps given. I get the correct error page.
This has been possibly fixed by an earlier PR.
![Uploading Screen Shot 2016-11-23 at 15.34.56.png…]()

**Comment by thijskh** [comment]
I cannot reproduce this anymore in EB 5.0. We were running 4.7 at the time this issue was reported. Likely it has been fixed in 5.0.
