### ISSUE TITLE
coin:guest_qualifier=some doesn't work in EB5

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#300]
In EB5, coin:guest_qualifier=some doesn't seem to be working: the isMemberOf attribute received from the IdP is ignored and an empty list is sent tot the SP.
the values "All" and "None" work as expected.

**Comment by thijskh** [comment]
I cannot reproduce this. How/where are you seeing this behaviour?

**Comment by thijskh** [comment]
Are you referring literally to the isMemberOf attribute? Because that is not how it works. You need to set `urn:oid:1.3.6.1.4.1.1076.20.100.10.10.1` as per https://wiki.surfnet.nl/display/coin2011/DEV-US0084.
This is how it has been working for years, I'm not aware of any changes in that in EB5.

**Comment by baszoetekouw** [comment]
I saw this behaviour on Bart's Openconext Workshop VM.  There, users from the DIY IDP for which isMemberOf:surf  is set were not allowed to create teams in SURFteams.  It might indeed be the case that the DIY-IdP is malfunctioning here and sending an incorrect attribute; I cannot check this now as the Infoserver is still down.

**Comment by thijskh** [comment]
The DIY IdP indeed sends both a different attribute and a different value.

**Comment by baszoetekouw** [comment]
The DIY IdP sends the following attribute:
```xml
         <saml:Attribute Name="urn:oid:1.3.6.1.4.1.5923.1.5.1.1"
            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
            <saml:AttributeValue xsi:type="xs:string">urn:collab:org:surf.nl</saml:AttributeValue>
         </saml:Attribute>
```
