### ISSUE TITLE
consent_date and usage_date updated on login

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#316]
In the `consent` table, both `consent_date` _and_ `usage_date` are updated on login, also when the user had previously accessed the service.

In any case `consent_date` should not be updated when logging in to something that one has already given consent for, so that's a bug to be fixed. I wonder though if we should keep `usage_date` at all. This causes one write per login to our database. Nicer approaches are possible that can avoid this number of writes.

This has been observed in 4.7 and 5.0 (but may be the case much longer already).

**Comment by thijskh** [comment]
`consent` should always only store the date of (first) consent, no longer the date of last use.

**Comment by DRvanR** [comment]
not storing the `last_usage` could make it hard to detect consents that have not been used for X amount of time. Could for instance be relevant if a given consent expires (or could expire) after a certain period. I don't think something like that exists at the moment, but removing the field removes that possibility as well. Not sure if that is even needed/wanted, but wanted to point it out just to be sure.

**Comment by thijskh** [comment]
Thanks. We're aware of that.

**Comment by arothuis** [comment]
Done in #367 and OpenConext/OpenConext-profile#73
