### ISSUE TITLE
Issues with coin:display_unconnected_idps_wayf

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#321]
On test2, I've discovered several issues with this feature:
1. After disabling access from 'thkidp' to Profile, the IdP still shows up in the WAYF
2. After enabling coin:display_unconnected_idps_wayf, below the list of IdPs a new element appears containing the text "Can't find your institution?  Request access or try tweaking your search.". This should only appear if the search results return in 0 matches. It should appear where it would otherwise (when coin:display_unconnected_idps_wayf is disabled) say "Your search did not return any results.".
3. If I recall correctly, the design of the WAYF contains a feature where all IdPs that do _not_ have access to an SP, appear below the ones that _do_ have access, with a "Request Access" button. Clicking it should open the request access form.
4. Submitting the request access form doesn't work, it also doesn't return an error.

![screen shot 2016-08-17 at 16 56 23](https://cloud.githubusercontent.com/assets/8791564/17741439/7174f7b6-649c-11e6-9249-b31d053911a8.png)

**Comment by thijskh** [comment]
Fixed in #429
