### ISSUE TITLE
Invalid idps metadata genererated when an IdP is missing an OrganizationDisplayName

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-engineblock#33]
Invalid metadata can be generated by EB:
```xml
<md:Organization>
        <md:OrganizationName xml:lang="en">name</md:OrganizationName>
        <md:OrganizationURL xml:lang="en">http://url</md:OrganizationURL>
    </md:Organization>
```

This causes some SPs (e.g. the Shib SP) to refuse the metadata.

The fragment above is not valid according to the XSD: 
```xml
<complexType name="OrganizationType">
    <sequence>
        <element ref="md:Extensions" minOccurs="0"/>
        <element ref="md:OrganizationName" maxOccurs="unbounded"/>
        <element ref="md:OrganizationDisplayName" maxOccurs="unbounded"/>
        <element ref="md:OrganizationURL" maxOccurs="unbounded"/>
    </sequence>
    <anyAttribute namespace="##other" processContents="lax"/>
</complexType>
```

When ```xml<md:Organization>``` is present it MUST contain:
- md:OrganizationName
- md:OrganizationDisplayName
- md:OrganizationURL
in the order given in the sequence.

The Organization element itself is optional. When not all required values are present Organization should be omitted.

**Comment by thijskh** [comment]
This has been fixed sometime since. Current EB does not output the block if any of the constituating elements is absent.
