### ISSUE TITLE
Pretty print compiled application.css instead of minimised version

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-engineblock#339]
If a deployer of OpenConext wants to make fast and minimal changes to WAYF web/stylesheets/application.css, she is confronted with a minimised version of application.css. She would need to unminimise this file before making (small) changes like corporate identity colors when recompiling the metro theme would require installation of all sorts of supporting engines and compilers.

**Comment by baszoetekouw** [comment]
IMO, there is no need for minimizing in the first place, as gzip compression is much better than whatever minimizing scheme is used.  (This would require enabling transparent gzip compression in the http-server, obviously.)

**Comment by relaxnow** [comment]
Does appear to add little: https://css-tricks.com/the-difference-between-minification-and-gzipping/
Especially as SASS already concatenates everything.

**Comment by thijskh** [comment]
I think the modern theming solves this in a better way than hacking things into the application.css directly.
