### ISSUE TITLE
Engineblock allows connection from a non existing RequesterID

### ISSUE THREAD

**Issue by quartje** [OpenConext/OpenConext-engineblock#347]
When an authentication request comes with a RequesterID comes in, and the entity of the RequesterID does not exist, Engineblock still allows authentication, using the issuer as entityid. This should not happen, EB should block the request.

**Comment by thijskh** [comment]
I'm assuming this (the problem and solution) only applies when `coin:trusted_proxy` is set for the Issuer.

**Comment by quartje** [comment]
This currently leads to an error: " dissimilar workflow states"

**Comment by thijskh** [comment]
Closed in  #433
