### ISSUE TITLE
EngineBlock 5.1.0 Debug tool returning "htmlspecialchars() expects parameter 1 to be string" error

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-engineblock#358]
Hello,

We recently upgraded to EB 5.1.0  and noticed the following error through the sp debug tool under Attributes after authenticating with our IdP: 
```
Identifier	urn:oid:1.3.6.1.4.1.5923.1.1.1.10	
Warning: htmlspecialchars() expects parameter 1 to be string, array given in /opt/openconext/OpenConext-engineblock-5.1.0/library/EngineBlock/View.php on line 204
```
The Array store in this variable looks like: `Array ( [Value] => bd7057e48ad9b3cbdca7a305f14bf448c730d1c1 [SPNameQualifier] => https://engine.dev.openconext.org/authentication/sp/metadata ) `

I confirmed that version 5.0.0 works as expected:
```
Identifier	urn:oid:1.3.6.1.4.1.5923.1.1.1.10	bd7057e48ad9b3cbdca7a305f14bf448c730d1c1
```

PS: I tried to do a `git bisect` to figure out exactly which commit was the cause of this..  But I noticed that after running the `composer prepare-env`  as per the README, it's looking for a `vendor` folder that doesn't exist in the repo and winds up failing. 

Thanks!

**Comment by arothuis** [comment]
Thanks for the issue report.

This probably has to do with changes in how EPTIs are being dealt with in SAML2 (I think). I will try and replicate this.

**Comment by arothuis** [comment]
I currently have no IdP that sends EPTI's. It goes wrong in the following bit of code:
```
                  <td>
                      <?php /** Single attribute value */ if (count($attributeValues)==1) { ?>
                      <?= EngineBlock_View::htmlSpecialCharsText($attributeValues[0]);?>
                      <?php } /** Multiple attribute values */ else { ?>
                      <ul>
                          <?php foreach ($attributeValues as $value) { ?>
                          <li><?= EngineBlock_View::htmlSpecialCharsText($value); ?></li>
                          <?php } ?>
                      </ul>
                      <?php } ?>
                  </td>
```

IIRC, `SAML2` has been changed to interpret EPTIs as multiple values, so the `$value` could contain an array representation of that value.

If this is indeed the culprit, a fix would be to check if `$value` is an array. If it is, we are dealing with an EPTI and the appropriate string representation should be handed over to the `htmlSpecialCharsText` method.

**Comment by precurse** [comment]
Awesome.  Thanks for the quick response guys.

Let me know if there's any testing you'd like us to do.. We're more than happy to help.
