### ISSUE TITLE
RequestDenied leads to an invalid reponse error

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#374]
<samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder">
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:RequestDenied" />
    </samlp:StatusCode>
</samlp:Status>

Leads to an "Error - Invalid Identity Provider response"

This should probably lead to a more descriptive error...
In my specific case, the IdP (ADFS) refuses to authenticate a user because a pre-condition (Issuance auth rule) has not been met.

**Comment by thijskh** [comment]
This is #61 and has/will be fixed in 5.2.

**Comment by tvdijen** [comment]
Ah crap, I scanned the issues but missed that one.. Sorry!
