### ISSUE TITLE
debug page broken in EB 5.2 (authentication procedure has not been authenticated)

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#380]
After migrating to EB 5.2.0 I can't seem to get EB working anymore.
The migration itself went fine, no errors or anything.
However, when I try to use the debug-tool and authenticate against an IdP, I get the following error:

> Jan 31 15:46:18 gdisx7006 EBLOG[23048]: [2017-01-31 15:46:18] engineblock.ERROR: Current authentication procedure cannot be completed: authentication procedure has not been authenticated | Caught Unhandled generic exception {"session_id":"25co32gpfir023p3ue7alhjje2","request_id":"5890a3398a0f8"} {"exception":{"severity":"ERROR","location":"/apps/components/engineblock/OpenConext-engineblock-5.2.0/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php:63","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Current authentication procedure cannot be completed: authentication procedure has not been authenticated\n#0 [internal function]: OpenConext\\EngineBlockBundle\\EventListener\\FallbackExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#1 /var/cache/openconext/engineblock/prod/classes.php(2646): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#2 /var/cache/openconext/engineblock/prod/classes.php(2579): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#3 /var/cache/openconext/engineblock/prod/classes.php(2740): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#4 /apps/components/engineblock/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3141): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#5 /apps/components/engineblock/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3077): Symfony\\Component\\HttpKernel

When I try and use the Profile-SP, I never even get to see the WAYF-page and end up with the 'Stuck in authentication loop' error right away (which is funny since I've never authenticated against an IdP at that point).
Since the latter is new functionality I suspect a bug, but some help/advise is greatly appreciated!

**Comment by tvdijen** [comment]
As per mailinglist discussion:  https://groups.google.com/forum/#!topic/openconext/BjhuN8PIkSc

**Comment by DRvanR** [comment]
Hey @tvdijen,

could you please verify whether or not the file `{project_root}/app/config/ini_parameters.yml` contains the settings `time_frame_for_authentication_loop_in_seconds` and `maximum_authentication_procedures_allowed` and what their respective values are?

Thanks in advance!

As an aside: that mailing list is not public, if there is any relevant information please copy it here.

**Comment by tvdijen** [comment]
All relevant info from the mailinglist is in my first post. The settings in ini_parameters.yml are set as follows:

>     time_frame_for_authentication_loop_in_seconds: 60
>     maximum_authentication_procedures_allowed: 5

**Comment by DRvanR** [comment]
Cheers, much appreciated!

As I cannot look at this issue in depth for now, I'm going to ping @arothuis to take a look at this. However, he is ill at the moment. We'll try to get back to you asap, but this probably will not be before next week.

**Comment by tvdijen** [comment]
No rush!  It's only my test-environment that's broken now and I can always do a rollback to 5.1.1 if I really need the environment..

**Comment by thijskh** [comment]
I've asked the list owner why the list is not publically readable.

**Comment by thijskh** [comment]
Yes, I can reproduce the exact same issue you have, when going to the debug page at `https://engine.example.org/authentication/sp/debug`. See output below.

Logging in to 'regular' SPs, like SR, works fine. It should be noted that the debug page is not an SP in any real sense of the word, but a special location inside Engineblock. So likely the authentication loop checking code has not factored this in? And there's no functional test for the debug page I guess?

Your remarks about e.g. Profile are likely unrelated. You should look in profile's logs for the loop, this might be related to OpenConext/OpenConext-profile#53. Let's keep this issue just about the debug page not working in 5.2.0, for clarity.

```
Feb 15 17:44:00 octest EBLOG[31323]: [2017-02-15 17:44:00] engineblock.ERROR: Current authentication procedure cannot be completed: authentication procedure has not been started | Caught Unhandled generic exception {"session_id":"Q4LFUzuA4DRvWUbw32ZuJTKAXo8","request_id":"58a4854fe41f2"} {"exception":{"severity":"ERROR","location":"/opt/openconext/OpenConext-engineblock-5.2.0/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php:63","userId":null,"idp":null,"sp":null,"details":"EngineBlock_Exception: Current authentication procedure cannot be completed: authentication procedure has not been started\n#0 [internal function]: OpenConext\\EngineBlockBundle\\EventListener\\FallbackExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#1 /opt/openconext/OpenConext-engineblock-5.2.0/app/cache/prod/classes.php(2646): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#2 /opt/openconext/OpenConext-engineblock-5.2.0/app/cache/prod/classes.php(2579): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#3 /opt/openconext/OpenConext-engineblock-5.2.0/app/cache/prod/classes.php(2740): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#4 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3141): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#5 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3077): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(OpenConext\\EngineBlockBundle\\Exception\\LogicException), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 /opt/openconext/OpenConext-engineblock-5.2.0/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#9 {main}\n\nOpenConext\\EngineBlockBundle\\Exception\\LogicException: Current authentication procedure cannot be completed: authentication procedure has not been started\n#0 /opt/openconext/OpenConext-engineblock-5.2.0/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(67): OpenConext\\EngineBlockBundle\\Authentication\\AuthenticationState->completeCurrentProcedure()\n#1 [internal function]: OpenConext\\EngineBlockBundle\\Controller\\ServiceProviderController->consumeAssertionAction()\n#2 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /opt/openconext/OpenConext-engineblock-5.2.0/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#7 {main}","message_prefix":null},"previous_exceptions":["exception 'OpenConext\\EngineBlockBundle\\Exception\\LogicException' with message 'Current authentication procedure cannot be completed: authentication procedure has not been started' in /opt/openconext/OpenConext-engineblock-5.2.0/src/OpenConext/EngineBlockBundle/Authentication/AuthenticationState.php:99\nStack trace:\n#0 /opt/openconext/OpenConext-engineblock-5.2.0/src/OpenConext/EngineBlockBundle/Controller/ServiceProviderController.php(67): OpenConext\\EngineBlockBundle\\Authentication\\AuthenticationState->completeCurrentProcedure()\n#1 [internal function]: OpenConext\\EngineBlockBundle\\Controller\\ServiceProviderController->consumeAssertionAction()\n#2 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /opt/openconext/OpenConext-engineblock-5.2.0/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /opt/openconext/OpenConext-engineblock-5.2.0/web/app.php(22): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#7 {main}"]}
```
