### ISSUE TITLE
EB 5.1 stores selectedIdps only with Session length

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#386]
Since the JS refactoring in EB 5.1, the `selectedidps` cookie is only set with a duration of "session". This means it will be forgotten if the user closes his/her browser. It used to have a lifetime of a year.

Compare:
https://github.com/OpenConext/OpenConext-engineblock/blob/5.0.2/theme/material/javascripts/application.js#L360
https://github.com/OpenConext/OpenConext-engineblock/blob/5.1.1/theme/material/javascripts/modules/PreviousSelectionStorage.js#L16

**Comment by arothuis** [comment]
Closing as it has been implemented in 5.2.2 in #388 and backported to 5.1.2 in #390.
