### ISSUE TITLE
Add support for IsPassive="true"

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-engineblock#39]
The current implementation of IsPassive consists of passing this value thru to the home IdP (similar to ForceAuthn). 
From os-core section 3.4.1: "If [IsPassive is] 'true', the identity provider and the user agent itself MUST NOT visibly take control of the user interface from the requester and interact with the presenter in a noticeable fashion"

The implementation if IsPassive in OpenConext is not complete:
- OpenConext can show a WAYF if the user has no session, this should not happen. Instead;
- when passive is not possible OpenConext should respond with a SAML Status, since we cannot show an error to a user:
  samlp:Status
      <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder">
          <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:NoPassive" />
      /samlp:StatusCode
  /samlp:Status

Also in case of other errors we should pass a status code to the IdP.

Because OpenConext passes IsPassive to the home IdP (as it should), OpenConext should expect and be able to handle a status code from the IdP.

**Comment by thijskh** [comment]
I researched this issue and these are the conclusions:

When receiving an IsPassive authnrequest, EB:
- sends a correct NoPassive response when >1 IdP is connected to this SP;
- sends a correct IsPassive authnrequest when 1 IdP is connected to this SP;
- processes an assertion correctly when this IdP decides to return one;
- throws an exception and shows the error screen "Identity Provider error" when the IdP returns a NoPassive response.

Only the last bullet is incorrect behaviour. The correct behaviour is that if EB receives a NoPassive from the IdP, it should similarly send out a NoPassive message to the SP.
