### ISSUE TITLE
What is class SurfConext_Identity and is it still needed?

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-engineblock#392]
Is this still necessary?
https://github.com/OpenConext/OpenConext-engineblock/tree/master/library/SurfConext

**Comment by arothuis** [comment]
This class was (is?) used for authentication purposes in [Surfnet_Zend_Helper_Authenticate's `direct` method](https://github.com/OpenConext/OpenConext-engineblock/blob/810121a490da53fa3921d88b2caf58ed6e433239/library/Surfnet/Zend/Helper/Authenticate.php#L28), but I cannot find evidence of it being called anywhere.

**Comment by thijskh** [comment]
Would be nice if it could be dropped then

**Comment by thijskh** [comment]
Fixed in #397
