### ISSUE TITLE
Improve WAYF for guest access

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#417]
As a guest user, it is currently very unclear which IdP I must use to login to a service. All I see is a list of institutions I don't belong to. It is not explained anywhere which one I have to select or which search query I should use.

This can be improved, by dividing the IdPs into different categories and tabs. There are 3 potential categories to implement:
1) Login using an institutional account (for the "default" IdPs)
2) Login using a personal account (for guest IdPs)
3) Login using an "other" IdP (for other external IdPs, from other domains for instance)

(Please note: these texts can and should probably be improved.)

When using the search field to find an IdP, I do want to see the results from *all* tabs, not just the one currently selected.

Also, this means SR should be able to discern between these categories. Probably an extra metadata field is required.

Last: this option should be made configurable. It should still be possible to only display 1 "category", even if some IdPs are guest IdPs.

See attached a mockup of just the first 2 categories.

![wayf2](https://cloud.githubusercontent.com/assets/8791564/25998768/c1deafc2-3722-11e7-9674-845da55b9d8b.png)
![wayf](https://cloud.githubusercontent.com/assets/8791564/25998769/c1fbb54a-3722-11e7-913f-ff650ac70e3e.png)

**Comment by thijskh** [comment]
Fixed in 6.4
