### ISSUE TITLE
engine block hostname gathering faild

### ISSUE THREAD

**Issue by mkoyan44** [OpenConext/OpenConext-engineblock#422]
Dear Comunity,
Engine block unable to get the hostname from a header of POST request.The ServerName in apache config set right the name of EngineBlock FQDN.Please see the code block and error log.Thx

Code:
   public function getHostname()
    {
        $configHostname = $this->getConfiguration()->get('hostname');
        if (is_string($configHostname) && !empty($configHostname)) {
                return $configHostname;
        }

        $httpRequestHostname = $_SERVER['HTTP_HOST'];
        $validator = new Zend_Validate_Hostname();
        if ($validator->isValid($httpRequestHostname)) {
            return $httpRequestHostname;
        }

        // throw new EngineBlock_Exception('No hostname configured and Host header is invalid.');
        throw new EngineBlock_Exception('No hostname configured and Host header is invalid.');

    }

LOG: 

 engineblock.ERROR: No hostname configured and Host header is invalid. | Caught Unhandled EngineBlock_Exception {"session_id":"WuKx9mbG1xYfSF3CWJcw3-9VPLb","request_id":"5941473b94f57"} {"exception":{"severity":"ERROR","location":"/opt/openconext/OpenConext-engineblock-5.3.0/library/EngineBlock/ApplicationSingleton.php:346","userId":null,"idp":null,"sp":null,"details"

**Comment by thijskh** [comment]
Is a hostname set in `/etc/openconext/engineblock.ini`?

**Comment by tvdijen** [comment]
Shouldn't this code use `$_SERVER['SERVER_NAME']` instead of the `$_SERVER['HTTP_HOST']` variable (which is not mandatory for HTTP/1.0)?

**Comment by thijskh** [comment]
I don't know of any clients that do not send `Host:`. That breaks virtual hosting which is very common nowadays.

**Comment by mkoyan44** [comment]
Hi Everyone,
Thanks for fast reply.

Hostname doesn't set in engineblock.ini file.How can set it properly?

**Comment by tvdijen** [comment]
`hostname = engine.demo.openconext.org` -  Change it to whatever your domain is

I still wonder why the HTTP_HOST variable is not set in your case...

**Comment by mkoyan44** [comment]
It's working.Thanks
