### ISSUE TITLE
oid attributes fail validation on debug page

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-engineblock#45]
The engine IdP debug page (https://engine.demo.openconext.org/authentication/sp/debug) has a few bigger and smaller issues, also see attached screenshot
![selection_059](https://cloud.githubusercontent.com/assets/1491826/3442382/d6403f92-0112-11e4-9d8e-12b7046cd785.jpg)

1) An image seems to be missing in the top left
2) When using an IdP that provides urn:OID attributes only, like e.g. surfnets DIY IdP, the debug page incorrectly reports various attributes (I assume UID and SHO) cannot be validated, however login in connected services works as engine does correctly interpret the right urn:OID attributes.
3) Various urn:OID attributes are not mapped to normal, descriptive displaynames

To reproduce, login via the DIY IdP with user student5 pass: student5

**Comment by thijskh** [comment]
The friendly name is now displayed correctly.

What's still open now is:
* Reports that "urn:mace:dir:attribute-def:uid requires at least 1 values" while IdP sends urn:oid:0.9.2342.19200300.100.1.1, which will work with EngineBlock.
