### ISSUE TITLE
Handle SAML response with status other than Success

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-engineblock#47]
The home IdP of a user can respond with a SAML Status element with a StatusCode other than "urn:oasis:names:tc:SAML:2.0:status:Success". 

We need to handle this better.

* Show status to user in readable form. See saml-core-2.0-os section 3.2.2.2 for a more readable version.
* Some status code require action form engine:
- AuthnFailed : Typically sent when a user chooses cancel on the IdP. We should forward status to SP.
- NoPassive : For passive request: Forward status to SP.
* Optional StatusMessage: Show in message to user

RequestDenied
AuthnFailed

**Comment by thijskh** [comment]
This is handled in #48 (AuthnFailed) and #61 (RequestDenied).
