### ISSUE TITLE
Debug SP Errors with EngineBlock 5.6.5

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-engineblock#522]
We just updated to EngineBlock 5.6.5 using OpenConect-deploy 238.1, but started getting the following errors through the sp/debug tool:

```
NameID | Fatal error: Cannot use object of type SAML2\XML\saml\NameID as array in /opt/openconext/OpenConext-engineblock-5.6.5/app/Resources/views/modules/Authentication/View/Proxy/debugidpresponse.phtml on line 106A very serious error occurred, it has been logged and sent to the administrator.

array (
  'type' => 1,
  'message' => 'Cannot use object of type SAML2\\XML\\saml\\NameID as array',
  'file' => '/opt/openconext/OpenConext-engineblock-5.6.5/app/Resources/views/modules/Authentication/View/Proxy/debugidpresponse.phtml',
  'line' => 106,
)
````

This issue goes away when I revert back to 5.5.5 (or 5.5.2)

Thanks

**Comment by thijskh** [comment]
This surprises me because if I look in the source that point does not use the object as an array (anymore): https://github.com/OpenConext/OpenConext-engineblock/blob/5.6.5/app/Resources/views/modules/Authentication/View/Proxy/debugidpresponse.phtml#L106

Are you perhaps overriding these (theme) files in some way?

**Comment by precurse** [comment]
Ahh, that might be the cause. Yeah, we did have to create a custom theme to take care of some customization (URLs and branding) that aren't changeable by the `engineblock.ini` config file.

I'll re-fork the latest theme and make the branding customizations again.. Closing the ticket.
