### ISSUE TITLE
5.7: The parameter "cookie.path" must be defined

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#526]
It needs mentioning in the upgrade notes that `cookie.path` has become a mandatory setting.

**Comment by thijskh** [comment]
I don't think it is in fact mandatory, if `cookie_path` is not found in `engineblock.ini`, `/` is used as default.

**Comment by tvdijen** [comment]
I don't recall the exact issue since it's been such a long time ago, but I think you're right..
