### ISSUE TITLE
Temporary Travis action for security checker can be removed when upgrading to PHP 7.2 or 7.1.18

### ISSUE THREAD

**Issue by arothuis** [OpenConext/OpenConext-engineblock#537]
In the [build.xml](https://github.com/OpenConext/OpenConext-engineblock/blob/fd5c24897240b3083ee3206d63aa5208baf4170a/build.xml#L90-L99), a temporary fix was introduced in order to deal with Symfony's security checker change to HTTPS / TLS and Travis' troubles dealing with this.

This has been [fixed in Travis](https://github.com/travis-ci/travis-ci/issues/6339#issuecomment-393297732) for PHP versions 7.2 and 7.18 and up by using OpenSSL instead of GnuTLS.

When upgrading to a more [modern PHP version](http://php.net/supported-versions.php), consider using the correct [security-checker action](https://github.com/OpenConext/OpenConext-engineblock/blob/fd5c24897240b3083ee3206d63aa5208baf4170a/build.xml#L83) in the build.xml instead.

See: sensiolabs/security-checker#73, travis-ci/travis-ci#6339, sensiolabs/security-checker#77.

The PR that introduced this: OpenConext/OpenConext-engineblock#407.

**Comment by thijskh** [comment]
@MKodde

**Comment by MKodde** [comment]
This temporary fix has been removed in 54126f55 and has been in EB releases since release 5.9.

Closing this issue
