### ISSUE TITLE
WAYF does not remember last selected IdP

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-engineblock#60]
Steps to reproduce:
1) Cleanup cookies related to IdP selection by WAYF (engine.surfconext.org "selectedIdP")
2) Login using IdP 1
3) login to another SP. The WAYF will now correctly present IdP 1 as the pre selection
4) Use IdP 2 to login
5) Login to yet another SP
6) WAYF will now present IdP1, not IdP 2
It should however preselect IdP 2

My cookies:
Host:                 engine.surfconext.nl
Name:                 selectedIdp
Path:                 /authentication/idp/
Content:              https%3A%2F%2Fidp.surfnet.nl
Content raw:          https%3A%2F%2Fidp.surfnet.nl
Expires:              di 04 nov 2014 17:08:38 CET
Expires raw:          1415117318
Send for:             Any type of connection
Send for raw:         false
Created:              wo 02 apr 2014 10:35:16 CEST
Created raw:          1396427715874516
Last accessed:        di 05 aug 2014 09:36:51 CEST
Last accessed raw:    1407224210813410
HTTP only:            No
HTTP only raw:        false
This domain only:     No
This domain only raw: false
Policy:               no information available
Policy raw:           0
Status:               no information available
Status raw:           0
---
Host:                 engine.surfconext.nl
Name:                 selectedIdp
Path:                 /authentication/idp/process-wayf/
Content:              https%3A%2F%2Fidp.surfnet.nl
Content raw:          https%3A%2F%2Fidp.surfnet.nl
Expires:              di 04 nov 2014 09:17:28 CET
Expires raw:          1415089048
Send for:             Any type of connection
Send for raw:         false
Created:              do 03 apr 2014 10:38:41 CEST
Created raw:          1396514320920783
Last accessed:        ma 04 aug 2014 17:08:39 CEST
Last accessed raw:    1407164918665488
HTTP only:            No
HTTP only raw:        false
This domain only:     No
This domain only raw: false
Policy:               no information available
Policy raw:           0
Status:               no information available
Status raw:           0
---
Host:                 engine.surfconext.nl
Name:                 selectedIdp
Path:                 /authentication/idp/single-sign-on/
Content:              https%3A%2F%2Fidp.surfnet.nl
Content raw:          https%3A%2F%2Fidp.surfnet.nl
Expires:              di 04 nov 2014 10:29:22 CET
Expires raw:          1415093362
Send for:             Any type of connection
Send for raw:         false
Created:              do 03 apr 2014 14:46:40 CEST
Created raw:          1396529200317684
Last accessed:        di 05 aug 2014 09:36:51 CEST
Last accessed raw:    1407224210813410
HTTP only:            No
HTTP only raw:        false
This domain only:     No
This domain only raw: false
Policy:               no information available
Policy raw:           0
Status:               no information available
Status raw:           0
---
Host:                 engine.surfconext.nl
Name:                 selectedIdp
Path:                 /authentication/idp/single-sign-on/key:20140505/
Content:              http%3A%2F%2Fadfs.stenden.com%2Fadfs%2Fservices%2Ftrust
Content raw:          http%3A%2F%2Fadfs.stenden.com%2Fadfs%2Fservices%2Ftrust
Expires:              vr 31 okt 2014 13:34:06 CET
Expires raw:          1414758846
Send for:             Any type of connection
Send for raw:         false
Created:              ma 21 jul 2014 14:02:04 CEST
Created raw:          1405944124474926
Last accessed:        di 05 aug 2014 09:36:51 CEST
Last accessed raw:    1407224210813410
HTTP only:            No
HTTP only raw:        false
This domain only:     No
This domain only raw: false
Policy:               no information available
Policy raw:           0
Status:               no information available
Status raw:           0
---
Host:                 engine.surfconext.nl
Name:                 selectedIdp
Path:                 /authentication/idp/single-sign-on/vo:managementvo/
Content:              https%3A%2F%2Fidp.surfnet.nl
Content raw:          https%3A%2F%2Fidp.surfnet.nl
Expires:              za 25 okt 2014 14:10:30 CEST
Expires raw:          1414239030
Send for:             Any type of connection
Send for raw:         false
Created:              di 06 mei 2014 17:22:30 CEST
Created raw:          1399389750323423
Last accessed:        do 31 jul 2014 14:16:36 CEST
Last accessed raw:    1406808995821722
HTTP only:            No
HTTP only raw:        false
This domain only:     No
This domain only raw: false
Policy:               no information available
Policy raw:           0
Status:               no information available
Status raw:           0
---

**Comment by thijskh** [comment]
Fixed in EB 4.5.
