### ISSUE TITLE
Ability to hide or rename EN/NL locale values

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-engineblock#605]
Currently in the language switcher there isn't a way to override the EN (or NL) values. We have a second language (FR), we can still leverage the NL translation ability by using French translations instead. 

There doesn't appear to be a way to override the values from https://github.com/OpenConext/OpenConext-engineblock/blob/master/theme/material/templates/layouts/scripts/language-switcher.html.twig  (or hide the toggle entirely).

Would this type of functionality be of use for EngineBlock? If so, I can look at updating the needed fields and create a PR for it.

Thanks

**Comment by tvdijen** [comment]
You can hide the toggle pretty easily:
```
.comp-language {
    display: none
}
```

And there was a discussion on the mailinglist recently regarding the addition of other languages:
https://groups.google.com/forum/#!searchin/openconext/language$20to$20engineblock%7Csort:date/openconext/7xAEdW6vPAU/nGECBoSXAgAJ

**Comment by thijskh** [comment]
Indeed, currently if I'm correct not just the template but also other pieces of code assumes the two languages are EN and NL.

I'd certainly be open to a change that would make this more configurable. Indeed as Tim indicated, it might be beneficial to work with Domingos on this?

**Comment by precurse** [comment]
Thanks Thijs.

We're not as concerned with the values used internally by EngineBlock (i.e. `lang=nl` in the address bar) as we are with what's displayed on the page to the user on the page itself (at least for now). Ideally we'd have it configurable with `OpenConext-deploy`, but the quick fix for now is to fork the EngineBlock repo, modify the theme and then use the custom theme during deployment.

**Comment by thijskh** [comment]
We've discussed this and we'll make a configurable list of languages (e.g. "en,nl,pt") in each product; if the list has only one value no choice will be offered. All code that does something with langues (e.g. if isset displayname:en then ... elseif issuet displayname:nl ... etc) will be changed to loop over the configured languages instead. The value for this config option will obviously be settable centrally in openconext-deploy.

**Comment by precurse** [comment]
Perfect thanks! That sounds like it would work well for any number of languages offered.

This is what we're currently running with Ansible, which seems to do the trick (for now):

```
- name: Patch NL to FR
  lineinfile:
    path: "{{ openconext_releases_dir }}/OpenConext-engineblock/theme/material/templates/layouts/scripts/language-switcher.html.twig"
    regexp: '^(.*)>NL<(.*)$'
    line: '\1>FR<\2'
    backrefs: yes
```

The previous Twig templating work SURF did with EngineBlock has made it way easier to customize EngineBlock. Thanks!

**Comment by thijskh** [comment]
Since EB 6.2 this is configurable in parameters.yml, setting `enabled_languages`
