### ISSUE TITLE
Slow wayf

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-engineblock#640]
Several users are complaining that the WAYF is 'slow'. For example, it takes a while before you can enter text into the seach field and even when you do, it respons really slow.

Some users have issues with WAYF's that only contain ~10 IdPs but I personally only have the issue when going to https://engine.surfconext.nl/authentication/sp/debug

Another problem is that the search field is not active straight away, so starting to type does not lead to the expected result (filtering IdPs).

Could the WAYF be optimised in such a way that all _text_ is loaded withing microseconds, including the search capability, and the rest is loaded after that? If it's already done this way something seems to be causing issues.

**Comment by arnoutt** [comment]
Another report from a user (in Dutch):

"Ik heb dezelfde issue.
Ik heb het alleen als ik met de muis de focus in het veld zet.

Als ik met tab via het toetsenbord het veld selecteer gaat zoeken wel gewoon snel.
Het lijkt er op dat het probleem is dat met de muis op het veld klikken de focus niet altijd goed zet. 
(Of na zetten dat er iets de focus weer weghaalt)
Ik kan het ook op met wat meer moeite op windows reproduceren. "

**Comment by thijskh** [comment]
Fixed in:
    Prevent blurring the search bar #656
    Make sure the mouse responds after removing previous IdP selection #661
    Unconnected IdP mouse hover should also highlight the IdP #662

part of EB 5.9.
