### ISSUE TITLE
Superfluous log entries for disabled language

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-engineblock#927]
My logs are being spammed with:
Oct  6 12:58:27 sv1811043 EBLOG[31783]: [2020-10-06 12:58:27] app.WARNING: No PT displayName and name found for idp: http://sts.example.org/adfs/services/trust {"session_id":"7045n4glv09o9d3ob5kajscu1h","request_id":"5f7c4dd3626b0"} {"additional_info":{"severity":null,"location":null,"userId":null,"idp":"http://sts.example.org/adfs/services/trust","sp":null,"details":"","message_prefix":null}}

This happens for each and every IDP, every time the WAYF is shown.. This can hardly be a warning if the pt-language is not enabled.. As you can imagine, this is becomming really spammy real quick..
Even if it were enabled, I think `NOTICE` should be sufficient for this.. It always has a fallback to `name:en`, which is mandatory, and therefore can never break runtime.

**Comment by thijskh** [comment]
I agree with making it Notice as a good start.

Then, I think it's the right approach to just use the enabled-languages parameter to loop over and collect these things.

As a bit of history, originally EB just had "en" and "nl" and they are hardcoded everywhere. Then PT was added just in the same way. Only after, the setting was implemented, primarily for UI (what to show in localepicker on the webpages). So now a logical next step is to refactor the places where NL/EN/PT are all sequentially processed and change that to use the enabled-languages parameter to loop over.

**Comment by thijskh** [comment]
Fixed in 6.5: only the names for the language we're actually rendering are being looked up, so if you do not have PT enabled it will never trigger, and even if for that language a name is missing, the loglevel has been lowered to notice.
