### ISSUE TITLE
Use of IdP-specific endpoint by non-connected SPs

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#94]
Currently, when an SP sends an AuthnRequest to an IdP-specific endpoint (e.g., https://engine.surfconext.nl/authentication/idp/single-sign-on/d67f6b2a3375ecdb6c53f27b210d3d0e), and the specified IdP is not connected to the SP making the request, EB falls back to showing a WAYF with the IdPs that are connected for this SP.  If only a single IdP is connected, the user is even directly redirected to that IdP (on which he cannot log in).

This is pretty confusing behaviour for the user.  EB should probably show a (clear) error message to the user, referring him to his institution's admin contact.

The above scenario particularly occurs for eduGAIN-SPs: any eduGAIN-SP that (automatically) allows all IdPs, causes the above to occur.  For an example, see https://issues.surfnet.nl/browse/CXT-10399

**Comment by relaxnow** [comment]
![screen shot 2015-11-19 at 11 14 14](https://cloud.githubusercontent.com/assets/524386/11267977/5fe399b6-8ea6-11e5-8121-af44ef89541b.png)
![screen shot 2015-11-19 at 11 12 18](https://cloud.githubusercontent.com/assets/524386/11267976/5fdf4118-8ea6-11e5-99be-6ad013239fd8.png)
