### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by sergioloyola** [OpenConext/OpenConext-engineblock#971]
Good morning, I'm installing openConext, following the tutorial "Installation steps to deploy OpenConext on a single system other than the Vagrant VM centOS7". But it is giving me the following error:

TASK [authz-admin: Copy config for default clients and resource servers] ********************************************
fatal: [10.22.0.184]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute oidc_checkToken_secret'"}

My local workstation has LinuxMint 20 installed and Centos 7 server installed

**Comment by thijskh** [comment]
I see you have opened https://github.com/OpenConext/OpenConext-deploy/issues/300 which is indeed the better place, so I will close this one.
