### ISSUE TITLE
Make it also possible (and configurable) to use ePPN for the identifier instead of SHO+uid

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-engineblock#98]
For eduTEAMS we would like to only use ePPN-attribute and remove the requirement for SHO+uid.
Changes to be made:
- change the requiredAttribute function
- change the creation of the internal identifier
- change LDAP provisioning (for searches made bij API)
- Add configuration option to indicate the use of ePPN

**Comment by relaxnow** [comment]
Fixed in 4.4

**Comment by remold** [comment]
@relaxnow Can you explain how to change the required attributes from SHO+uid to ePPN?

There used to be a config option 'openConextIdentifierType', but this looks to be changed.

Thanks

**Comment by relaxnow** [comment]
@remold Requested / Required attributes are now taken from attribute definition file: https://github.com/OpenConext/OpenConext-engineblock/blob/master/application/configs/application.ini#L64
