### ISSUE TITLE
Remove remaining /etc/surfconext usage

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-engineblock#99]
After 'upgrading' from release 4.1 to 4.2 and the command:
mv /etc/surfconext /etc/openconext
the following error appears most of the EB webpages:
Warning: filemtime(): stat failed for /etc/surfconext/engineblock.ini in /opt/www/OpenConext-engineblock/library/EngineBlock/Cache/FileCacheProxyAbstract.php on line 55 

A workaround: create sym-link between /etc/surfconext /etc/openconext

**Comment by thijskh** [comment]
This has been done in Engineblock 5.0.
